version: '3.8'
services: 
    api-service:
        build: .
        volumes: 
            - .:/web
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
